# [mgr]
# prepend_keymap = [
#         { on = "z",      run = "plugin zoxide",        desc = "Jump to a directory via zoxide" },
#         { on = "<C-w>",  run = "close",                desc = "Close the current tab, or quit if it's last" },
#         { on   = "l",    run  = "plugin smart-enter",  desc = "Enter the child directory, or open the file" },
#         { on = "Z",      run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },
# ]

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "Jump to a directory via zoxide"

[[mgr.prepend_keymap]]
on = "<C-w>"
run = "close"
desc = "Close the current tab, or quit if it's last"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[manager.prepend_keymap]]
on = "n"
run = "open --with vim"
desc = "Open in Vim"

