[mgr]
ratio = [3, 5, 10]

[opener]
play = [ { run = '/home/daroch/.config/yazi/play.sh "$@"', orphan = true } ]

# # Example of adding Viewnior to the existing image rules
# [[open.prepend_rules]]
# mime = "image/*"
# use = [ "viewnior", "open" ]

# vim = [
#   { run = 'vim "$@"', block = true, for = "unix", desc = "Vim (lightweight)" }
# ]
#
# nvim = [
#   { run = 'nvim "$@"', block = true, for = "unix", desc = "Neovim (LSP / jdtls)" }
# ]
#
#
# [open]
# rules = [
#   { name = "*.java", use = [ "vim", "nvim" ] },
#   { mime = "text/*", use = ["nvim", "vim" ] },
# ]
